### ISSUE TITLE
Add data navigation to data feeds

### ISSUE THREAD

**Issue by rhyolight** [nupic-community/river-view#128]
If a user requests the data from a stream without a `limit`, `since`, or `until` parameter, and the resulting request to Redis takes too long to fetch because of the large quantity of data, the client's request will timeout. 

This issue is to put in place a data limit on the backend that prevents large data calls from timing out, as well as adding some type of data navigation strategy so users can move through the data easily. 

* * *

- [x] [Return 400 Bad Request when user submits `limit` && `since` && `until`](https://github.com/nupic-community/river-view/issues/134)
- [x] [Apply a default limit to every data request](https://github.com/nupic-community/river-view/issues/135)
- [x] [Queries with both "since" & "until" must be limited](https://github.com/nupic-community/river-view/issues/138)
- [x] [Add query param to tell where edge of data window should be](https://github.com/nupic-community/river-view/issues/139)
- [x] [Return navigation URLs with each JSON data response](https://github.com/nupic-community/river-view/issues/129)
- [x] [HTML data view should be paginated](https://github.com/nupic-community/river-view/issues/131)

**Comment by rhyolight** [comment]
Related to https://github.com/nupic-community/river-view/issues/82.
