### ISSUE TITLE
Add pagination to streams

### ISSUE THREAD

**Issue by rhyolight** [nupic-community/river-view#82]
It takes forever to load the streams HTML view, CSV, or JSON data. For example, the `mn-traffic-sensors` river has over 6,000 keys: <http://data.numenta.org/mn-traffic-sensors/keys.html> & <http://data.numenta.org/mn-traffic-sensors/keys.json>.

This task is to add pagination to the to streams view at `http://localhost:8085/<river-name>/keys.html`. This goes from `/site/templates/keys.html` to `/site/js/keys.js` to `/lib/data-server.js:119` (`handleRiverStreamsRequest`) and aaaaaaaall the way to the Redis client at `/lib/redis-client.js`.

* * *

- [x] [Add pagination options for Redis client getKeys()](https://github.com/nupic-community/river-view/issues/79)
- [x] [Redis client getKeys() results should be sorted by key](https://github.com/nupic-community/river-view/issues/78)
- [x] ~~[JSON requests for streams should respect pagination options](https://github.com/nupic-community/river-view/issues/80)~~
- [x] [HTML stream view should be paginated](https://github.com/nupic-community/river-view/issues/81)

**Comment by rhyolight** [comment]
@antidata Ever used Redis?
